#!/usr/bin/env bash
# =============================================================================
# post-install-hardening.sh
# Ubuntu / Debian post-install security hardening
#
# Usage:
#   sudo ./post-install-hardening.sh              # interactive
#   sudo ./post-install-hardening.sh --unattended # uses defaults, no prompts
#
# What this script does:
#   1.  System update
#   2.  SSH hardening
#   3.  UFW firewall (SSH restricted to LAN)
#   4.  sysctl kernel hardening
#   5.  fail2ban (SSH brute-force protection)
#   6.  auditd (system call audit logging + rules)
#   7.  Password policy (pwquality)
#   8.  Disable unnecessary services
#   9.  Fix daemon login shells
#   10. Security tools: rkhunter, lynis, acct, usbguard
#   11. Unattended upgrades (security only)
#   12. Final summary
# =============================================================================

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

ok()   { echo -e "${GREEN}✓${RESET} $*"; }
info() { echo -e "${CYAN}→${RESET} $*"; }
warn() { echo -e "${YELLOW}⚠${RESET} $*"; }
err()  { echo -e "${RED}✗${RESET} $*" >&2; }
hdr()  { echo -e "\n${BOLD}${CYAN}══ $* ══${RESET}"; }

die()  { err "$*"; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Run as root: sudo $0"

# ── OS detection ──────────────────────────────────────────────────────────────
if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    OS_ID="${ID:-unknown}"
    OS_VERSION="${VERSION_CODENAME:-unknown}"
else
    die "Cannot detect OS — /etc/os-release missing"
fi

[[ "$OS_ID" == "ubuntu" || "$OS_ID" == "debian" ]] || \
    die "Unsupported OS: $OS_ID. This script targets Ubuntu/Debian only."

info "Detected: ${PRETTY_NAME:-$OS_ID $OS_VERSION}"

# ── Mode ──────────────────────────────────────────────────────────────────────
UNATTENDED=false
[[ "${1:-}" == "--unattended" ]] && UNATTENDED=true

ask() {
    # ask <var> <prompt> <default>
    local var="$1" prompt="$2" default="$3"
    if $UNATTENDED; then
        eval "$var=\"$default\""
        return
    fi
    read -rp "$(echo -e "${CYAN}?${RESET} $prompt [$default]: ")" input
    eval "$var=\"${input:-$default}\""
}

confirm() {
    # confirm <prompt> <default y/n>
    local prompt="$1" default="${2:-y}"
    $UNATTENDED && return 0
    read -rp "$(echo -e "${CYAN}?${RESET} $prompt [${default}]: ")" ans
    ans="${ans:-$default}"
    [[ "$ans" =~ ^[Yy] ]]
}

# ── Detect primary non-root user ──────────────────────────────────────────────
PRIMARY_USER=$(getent passwd | awk -F: '$3>=1000 && $3<65534 && $7 !~ /nologin|false/{print $1}' | head -1)
PRIMARY_USER="${PRIMARY_USER:-$(logname 2>/dev/null || echo "")}"

# ── Detect LAN subnet ─────────────────────────────────────────────────────────
LAN_SUBNET=$(ip route | grep -v "^default\|virbr\|lo\|docker\|br-" | \
             awk '/scope link/{print $1}' | grep -v "^169\." | head -1)
LAN_SUBNET="${LAN_SUBNET:-192.168.1.0/24}"

# ── Collect settings ──────────────────────────────────────────────────────────
hdr "Configuration"

ask SSH_USER      "SSH AllowUsers (space-separated)"  "${PRIMARY_USER:-$USER}"
ask SSH_PORT      "SSH port"                           "22"
ask LAN_SUBNET    "LAN subnet for SSH access"         "$LAN_SUBNET"
ask SSH_AUTH_MODE "SSH auth mode (password/key/both)" "password"

info "User: $SSH_USER | Port: $SSH_PORT | Subnet: $LAN_SUBNET | Auth: $SSH_AUTH_MODE"
confirm "Proceed with hardening?" "y" || die "Aborted."

LOGFILE="/var/log/hardening-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee -a "$LOGFILE") 2>&1
info "Logging to $LOGFILE"

# =============================================================================
# 1. SYSTEM UPDATE
# =============================================================================
hdr "1 · System Update"
apt-get update -qq
apt-get upgrade -y -qq
ok "System up to date"

# =============================================================================
# 2. SSH HARDENING
# =============================================================================
hdr "2 · SSH Hardening"

SSH_DROPIN="/etc/ssh/sshd_config.d/99-hardening.conf"
cp /etc/ssh/sshd_config "/etc/ssh/sshd_config.bak.$(date +%Y%m%d)" 2>/dev/null || true

case "$SSH_AUTH_MODE" in
    key)      PW_LINE="PasswordAuthentication no" ;;
    both)     PW_LINE="PasswordAuthentication yes" ;;
    password|*) PW_LINE="PasswordAuthentication yes" ;;
esac

cat > "$SSH_DROPIN" << EOF
# Hardening — generated by post-install-hardening.sh $(date)
Port $SSH_PORT
PermitRootLogin no
$PW_LINE
AllowUsers $SSH_USER
MaxAuthTries 3
LoginGraceTime 30
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PrintLastLog yes
ClientAliveInterval 300
ClientAliveCountMax 2
Banner none
EOF

sshd -t && systemctl reload ssh
ok "SSH hardened → $SSH_DROPIN"

if [[ "$SSH_AUTH_MODE" == "key" ]]; then
    warn "Key-only mode set. Ensure your public key is in ~/.ssh/authorized_keys before logging out."
fi

# =============================================================================
# 3. UFW FIREWALL
# =============================================================================
hdr "3 · UFW Firewall"

apt-get install -y -qq ufw

ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw default deny forward

# SSH restricted to LAN subnet
ufw allow from "$LAN_SUBNET" to any port "$SSH_PORT" proto tcp comment "SSH LAN only"

# Allow established/related (implicit in ufw, but be explicit)
ufw logging on

ufw --force enable
ok "UFW enabled — SSH allowed from $LAN_SUBNET only"
ufw status verbose

# =============================================================================
# 4. SYSCTL KERNEL HARDENING
# =============================================================================
hdr "4 · Kernel Hardening (sysctl)"

cat > /etc/sysctl.d/99-hardening.conf << 'EOF'
# Network — stop sending/accepting redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Log suspicious packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

# SYN flood protection
net.ipv4.tcp_syncookies = 1

# Reverse path filtering (strict)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP broadcast/bogus errors
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Kernel hardening
kernel.randomize_va_space = 2
kernel.dmesg_restrict = 1
kernel.kptr_restrict = 2
kernel.yama.ptrace_scope = 1
kernel.perf_event_paranoid = 3

# BPF
kernel.unprivileged_bpf_disabled = 1

# Filesystem
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
fs.protected_fifos = 1
fs.protected_regular = 2
EOF

sysctl --system -q
ok "sysctl hardening applied"

# =============================================================================
# 5. FAIL2BAN
# =============================================================================
hdr "5 · fail2ban"

apt-get install -y -qq fail2ban

cat > /etc/fail2ban/jail.local << EOF
[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 3
banaction = nftables
banaction_allports = nftables[type=allports]
backend = systemd

[sshd]
enabled  = true
port     = $SSH_PORT
backend  = systemd
journalmatch = _SYSTEMD_UNIT=ssh.service + _COMM=sshd
maxretry = 3
bantime  = 3600
EOF

systemctl enable --now fail2ban
ok "fail2ban configured and running"

# =============================================================================
# 6. AUDITD
# =============================================================================
hdr "6 · auditd"

apt-get install -y -qq auditd audispd-plugins

cat > /etc/audit/rules.d/99-hardening.rules << 'EOF'
# Delete existing rules
-D

# Increase buffer size
-b 8192

# Identity changes
-w /etc/passwd  -p wa -k identity
-w /etc/shadow  -p wa -k identity
-w /etc/group   -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/sudoers -p wa -k sudoers
-w /etc/sudoers.d/ -p wa -k sudoers

# Auth log
-w /var/log/auth.log -p wa -k auth
-w /var/log/faillog  -p wa -k auth

# SSH config
-w /etc/ssh/sshd_config    -p wa -k sshd
-w /etc/ssh/sshd_config.d/ -p wa -k sshd

# Cron
-w /etc/cron.d/       -p wa -k cron
-w /etc/cron.daily/   -p wa -k cron
-w /etc/cron.weekly/  -p wa -k cron
-w /etc/cron.monthly/ -p wa -k cron
-w /etc/crontab       -p wa -k cron
-w /var/spool/cron/   -p wa -k cron

# Privilege escalation
-w /bin/su   -p x -k priv_esc
-w /usr/bin/sudo -p x -k priv_esc
-a always,exit -F arch=b64 -S execve -F euid=0 -F auid>=1000 -F auid!=-1 -k root_exec

# Network config changes
-a always,exit -F arch=b64 -S sethostname -S setdomainname -k network_mod
-w /etc/hosts         -p wa -k network_mod
-w /etc/network/      -p wa -k network_mod
-w /etc/NetworkManager/ -p wa -k network_mod

# Module loading
-w /sbin/insmod  -p x -k modules
-w /sbin/rmmod   -p x -k modules
-w /sbin/modprobe -p x -k modules
-a always,exit -F arch=b64 -S init_module -S finit_module -S delete_module -k modules

# Immutable flag (must be last)
-e 2
EOF

augenrules --load 2>/dev/null || service auditd restart
systemctl enable auditd
ok "auditd configured with hardening rules"

# =============================================================================
# 7. PASSWORD POLICY
# =============================================================================
hdr "7 · Password Policy"

apt-get install -y -qq libpam-pwquality

cat > /etc/security/pwquality.conf << 'EOF'
# Minimum length
minlen = 12
# Require at least 3 character classes (upper, lower, digit, special)
minclass = 3
# Max consecutive identical characters
maxrepeat = 3
# Check against username
gecoscheck = 1
# Don't allow dictionary words
dictcheck = 1
EOF

# Set password aging (optional — commented out for personal machines)
# chage --maxdays 180 --warndays 14 "$PRIMARY_USER" 2>/dev/null || true

ok "pwquality policy applied (min 12 chars, 3 classes)"

# =============================================================================
# 8. DISABLE UNNECESSARY SERVICES
# =============================================================================
hdr "8 · Unnecessary Services"

DISABLE_SERVICES=()

# Printer spooler — disable if cups/lpd not needed
if systemctl is-active --quiet lpd 2>/dev/null; then
    if confirm "Disable lpd (printer spooler)?" "y"; then
        systemctl disable --now lpd 2>/dev/null && DISABLE_SERVICES+=("lpd") || true
    fi
fi

# ModemManager — usually not needed on desktops without mobile dongles
if systemctl is-active --quiet ModemManager 2>/dev/null; then
    if confirm "Disable ModemManager (mobile broadband — needed for USB modems/SIMs)?" "y"; then
        systemctl disable --now ModemManager 2>/dev/null && DISABLE_SERVICES+=("ModemManager") || true
    fi
fi

# avahi-daemon — mDNS/Bonjour, not needed on most systems
if systemctl is-active --quiet avahi-daemon 2>/dev/null; then
    if confirm "Disable avahi-daemon (mDNS/Bonjour discovery)?" "y"; then
        systemctl disable --now avahi-daemon 2>/dev/null && DISABLE_SERVICES+=("avahi-daemon") || true
    fi
fi

if [[ ${#DISABLE_SERVICES[@]} -gt 0 ]]; then
    ok "Disabled: ${DISABLE_SERVICES[*]}"
else
    info "No services disabled"
fi

# =============================================================================
# 9. DAEMON LOGIN SHELLS
# =============================================================================
hdr "9 · Daemon Account Shells"

# System accounts (UID < 1000) should not have interactive shells
FIXED_SHELLS=()
while IFS=: read -r name _ uid _ _ _ shell; do
    if [[ "$uid" -gt 0 && "$uid" -lt 1000 ]]; then
        if [[ "$shell" == "/bin/sh" || "$shell" == "/bin/bash" ]]; then
            usermod -s /usr/sbin/nologin "$name"
            FIXED_SHELLS+=("$name")
        fi
    fi
done < /etc/passwd

if [[ ${#FIXED_SHELLS[@]} -gt 0 ]]; then
    ok "Set nologin shell for: ${FIXED_SHELLS[*]}"
else
    ok "All daemon accounts already have nologin/false shells"
fi

# =============================================================================
# 10. SECURITY TOOLS
# =============================================================================
hdr "10 · Security Tools"

TOOLS="rkhunter lynis acct"
apt-get install -y -qq $TOOLS

# rkhunter — build clean baseline
rkhunter --update --quiet 2>/dev/null || true
rkhunter --propupd --quiet 2>/dev/null || true
ok "rkhunter baseline built"

# rkhunter weekly cron
cat > /etc/cron.weekly/rkhunter-check << 'EOF'
#!/bin/bash
/usr/bin/rkhunter --cronjob --update --quiet
EOF
chmod +x /etc/cron.weekly/rkhunter-check
ok "rkhunter weekly scan scheduled"

# acct — process accounting
systemctl enable --now acct 2>/dev/null || true
ok "acct (process accounting) enabled"

# lynis — just ensure it's available, user runs it manually
ok "lynis installed — run: sudo lynis audit system"

# =============================================================================
# 11. UNATTENDED UPGRADES (security only)
# =============================================================================
hdr "11 · Unattended Security Upgrades"

apt-get install -y -qq unattended-upgrades

cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::Package-Blacklist {};
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-Time "04:00";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "14";
EOF

systemctl enable --now unattended-upgrades
ok "Unattended security upgrades configured"

# =============================================================================
# 12. SUMMARY
# =============================================================================
hdr "Hardening Complete"

echo
echo -e "${BOLD}SSH configuration:${RESET}"
echo "  Port:        $SSH_PORT"
echo "  AllowUsers:  $SSH_USER"
echo "  Auth mode:   $SSH_AUTH_MODE"
echo "  LAN access:  $LAN_SUBNET"
echo
echo -e "${BOLD}Services status:${RESET}"
for svc in ssh ufw fail2ban auditd unattended-upgrades arpwatch; do
    state=$(systemctl is-active "$svc" 2>/dev/null || echo "not-found")
    if [[ "$state" == "active" ]]; then
        echo -e "  ${GREEN}✓${RESET} $svc"
    else
        echo -e "  ${RED}✗${RESET} $svc ($state)"
    fi
done

echo
echo -e "${BOLD}Remaining manual steps:${RESET}"
echo "  1. sudo ufw status verbose          — verify firewall rules"
echo "  2. sudo lynis audit system          — full audit score"
echo "  3. sudo rkhunter --check            — rootkit scan"
echo "  4. Review $LOGFILE"

if [[ "$SSH_AUTH_MODE" == "key" ]]; then
    echo
    warn "KEY AUTH ENABLED — add your public key before closing this session:"
    echo "  ssh-copy-id -i ~/.ssh/id_ed25519.pub ${SSH_USER}@$(hostname -I | awk '{print $1}')"
fi

echo
ok "Log saved to: $LOGFILE"
